default:
  port: 4000
  redisServerIp: '10.29.3.221'
  redisServerPort: '6379'
  CIServer: 'http://10.29.3.221:8080'
  jobName: 'TASK-RUNNER'
  nginxServer: 'http://nginx/fs'
  taskServer: 'http://10.29.3.189'
  database: 'mongodb://localhost/twars'
  apiServer: 'http://localhost:8080/api'
